<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 ./cute_ghost/cute_ghost.glb -t
Author: P3D (https://sketchfab.com/PelpesElSabio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-ghost-2c8c03bb0e5049529e653f9011a8fc90
Title: Cute ghost
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	interface Props_1 {
		children?: import('svelte').Snippet<[any]>;
		[key: string]: any
	}

	let { children, ...rest }: Props_1 = $props();

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group>;

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Ground_M_Ground_0: THREE.Mesh;
			Ghost_M_Ghost_0: THREE.Mesh;
			Ghost001_M_Ghost_0: THREE.Mesh;
			Ghost002_Outline_0: THREE.Mesh;
		};
		materials: {
			M_Ground: THREE.MeshBasicMaterial;
			M_Ghost: THREE.MeshBasicMaterial;
			Outline: THREE.MeshBasicMaterial;
		};
	};

	const { gltf } = useGltf<GLTFResult>('/static/cute_ghost/cute_ghost.glb');
</script>

{#if $gltf}
	<Three type="{ref}" {...rest}>
		<T.Group scale="{0.01}">
			<T.Mesh
				geometry="{$gltf.nodes.Ground_M_Ground_0.geometry}"
				material="{$gltf.materials.M_Ground}"
				position="{[0, -1.79, 0]}"
				rotation="{[-Math.PI / 2, 0, 0]}"
				scale="{100}"
			/>
			<T.Mesh
				geometry="{$gltf.nodes.Ghost_M_Ghost_0.geometry}"
				material="{$gltf.materials.M_Ghost}"
				rotation="{[-Math.PI / 2, 0, 0]}"
				scale="{100}"
			/>
			<T.Mesh
				geometry="{$gltf.nodes.Ghost001_M_Ghost_0.geometry}"
				material="{$gltf.materials.M_Ghost}"
				rotation="{[-Math.PI / 2, 0, 0]}"
				scale="{100}"
			/>
			<T.Mesh
				geometry="{$gltf.nodes.Ghost002_Outline_0.geometry}"
				material="{$gltf.materials.Outline}"
				rotation="{[-Math.PI / 2, 0, 0]}"
				scale="{100}"
			/>
		</T.Group>

		{@render children?.({ ref, })}
	</Three>
{/if}
